=== JoseAntonioLiebanaDelgado/XML/Uf2_24_02_23/ex2/ex2.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
targetNamespace="https://www.w3schools.com"
xmlns="https://www.w3schools.com"
elementFormDefault="qualified">
  <xs:element name="editorial">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="libro" maxOccurs="unbounded">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="titulo" type="xs:string"/>
              <xs:element name="autor" type="xs:string" maxOccurs="unbounded" minOccurs="0"/>
              <xs:element name="premio" type="xs:string" minOccurs="0"/>
              <xs:element name="fechaPublicacion">
                <xs:complexType>
                  <xs:attribute name="año" type="xs:gYear"/>
                </xs:complexType>
              </xs:element>
              <xs:element name="codigoPostal">
                <xs:simpleType>
                  <xs:restriction base="xs:int">
                    <xs:totalDigits value="5"/>
                  </xs:restriction>
                </xs:simpleType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== JoseAntonioLiebanaDelgado/XML/Uf2_24_02_23/ex2/ex2.xml
<?xml version="1.0" encoding="UTF-8"?>
<editorial xmlns="https://www.w3schools.com"
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:schemaLocation="https://www.w3schools.com ex2.xsd">
  <libro>
    <titulo>El quinto punto cardinal</titulo>
    <autor>Javier Sachez</autor>
    <premio>Premio de novela Juan José Plans 2017</premio>
    <fechaPublicacion año="2017" />
    <codigoPostal>06253</codigoPostal>
  </libro>
  <libro>
    <titulo>Pantaleón y las visitadoras</titulo>
    <autor>Mario Vargas Llosa</autor>
    <premio>Premio Latinoamericano de Literatura</premio>
    <fechaPublicacion año="1973" />
    <codigoPostal>05683</codigoPostal>
  </libro>
  <libro>
    <titulo>Middletown: A study in american culture</titulo>
    <autor>Robert Lynd</autor>
    <autor>Helen Lynd</autor>
    <premio />
    <fechaPublicacion año="1929" />
    <codigoPostal>08024</codigoPostal>
  </libro>
</editorial>
