=== JoseAntonioLiebanaDelgado/XML/Uf2_24_02_23/ex1/ex1.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
targetNamespace="https://www.w3schools.com"
xmlns="https://www.w3schools.com"
elementFormDefault="qualified">
  <xs:element name="biblioteca">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="llibre" maxOccurs="unbounded">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="codi" type="xs:int"/>
              <xs:element name="titol" type="xs:string"/>
              <xs:element name="editorial" type="xs:string"/>
              <xs:element name="edicio" type="xs:int"/>
              <xs:element name="isbn" type="xs:string"/>
              <xs:element name="numPag" type="xs:int"/>
              <xs:element name="autor" type="xs:string"/>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== JoseAntonioLiebanaDelgado/XML/Uf2_24_02_23/ex1/ex1.xml
<?xml version="1.0" encoding="UTF-8"?>
<biblioteca xmlns="https://www.w3schools.com"
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:schemaLocation="https://www.w3schools.com ex1.xsd">
  <llibre>
    <codi>1</codi>
    <titol>Vientos de invierno</titol>
    <editorial>abcd</editorial>
    <edicio>2030</edicio>
    <isbn>12434354-5454-6465</isbn>
    <numPag>700</numPag>
    <autor>George R.R. Martin</autor>
  </llibre>
  <llibre>
    <codi>2</codi>
    <titol>Vientos de invierno</titol>
    <editorial>abcd</editorial>
    <edicio>2030</edicio>
    <isbn>12434354-5454-6465</isbn>
    <numPag>700</numPag>
    <autor>George R.R. Martin</autor>
  </llibre>
</biblioteca>
